### ISSUE TITLE
ImportError: No module named 'models' on db init

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#2]
```
$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
$ python manage.py db init

Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from app import application, db
  File "/home/raniere/gsoc/2016/prerit/Result-aggregation-server/app/__init__.py", line 7, in <module>
    from app import views, models
  File "/home/raniere/gsoc/2016/prerit/Result-aggregation-server/app/views.py", line 4, in <module>
    from models import UserSystemInfo, SuccessfulInstalls, FailedInstalls, Attempts
ImportError: No module named 'models'
```

**Comment by rgaiacs** [comment]
Close by #4.
