### ISSUE TITLE
Directory migrations already exists

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#36]
When I run `python manage.py db init` twice:

```
$ python manage.py db init
Traceback (most recent call last):
  File "manage.py", line 49, in <module>
    manager.run()
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_migrate/__init__.py", line 98, in init
    command.init(config, directory, 'flask')
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/command.py", line 29, in init
    raise util.CommandError("Directory %s already exists" % directory)
alembic.util.exc.CommandError: Directory migrations already exists
```

**Comment by prerit2010** [comment]
Please refer [this comment](https://github.com/prerit2010/Result-aggregation-server/issues/37#issuecomment-238108147)
