### ISSUE TITLE
Can't locate revision identified by '30dc7f6b846a'

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#37]
```
$ python manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 349, in _revision_for_ident
    revision = self._revision_map[resolved_id]
KeyError: '30dc7f6b846a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 129, in _catch_revision_errors
    yield
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 310, in _upgrade_revs
    revs = list(revs)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 610, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 359, in _revision_for_ident
    resolved_id)
alembic.script.revision.ResolutionError: No such revision or branch '30dc7f6b846a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 49, in <module>
    manager.run()
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/runtime/migration.py", line 303, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/command.py", line 163, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 314, in _upgrade_revs
    for script in reversed(list(revs))
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 160, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 121, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 114, in reraise
    raise value.with_traceback(tb)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 129, in _catch_revision_errors
    yield
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 310, in _upgrade_revs
    revs = list(revs)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 610, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 359, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by '30dc7f6b846a'
```

**Comment by prerit2010** [comment]
@rgaiacs  Flask-migrate creates a table named "alembic_version" in your database. So whenever you are creating a new database or something, you should delete the migrations folder and then only run the following commands : 
-  `python manage.py db init`
-  `python manage.py db migrate`
-  `python manage.py db upgrade`

**Comment by rgaiacs** [comment]
I'm replacing this with #50.

**Comment by njoanc** [comment]
When I try this, i got this error:
ERROR [root] Error: Can't locate revision identified by 'f87b488f1889'

**Comment by mjmakenzi** [comment]
drop "alembic_version" in your database..i try it fixed!

**Comment by nigohiroki** [comment]
If you use flask, I can solve below flow.

`flask db revision --rev-id 30dc7f6b846a `
`flask db migrate`
`flask db upgrade`
