### ISSUE TITLE
Can't locate revision identified by 'bea6982d2a4e'

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#50]
When I ran

```
$ git clone git@github.com:prerit2010/Result-aggregation-server.git && \
cd Result-aggregation-server && \
python manage.py db init && \
python manage.py db migrate && \
python manage.py db upgrade
```

I got

```
Cloning into 'Result-aggregation-server'...
remote: Counting objects: 964, done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 964 (delta 52), reused 0 (delta 0), pack-reused 857
Receiving objects: 100% (964/964), 185.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (565/565), done.
Checking connectivity... done.
  Creating directory /tmp/Result-aggregation-server/migrations ... done
  Creating directory /tmp/Result-aggregation-server/migrations/versions ... done
  Generating /tmp/Result-aggregation-server/migrations/script.py.mako ... done
  Generating /tmp/Result-aggregation-server/migrations/env.py ... done
  Generating /tmp/Result-aggregation-server/migrations/alembic.ini ... done
  Generating /tmp/Result-aggregation-server/migrations/README ... done
  Please edit configuration/connection/logging settings in '/tmp/Result-
  aggregation-server/migrations/alembic.ini' before proceeding.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 349, in _revision_for_ident
    revision = self._revision_map[resolved_id]
KeyError: 'bea6982d2a4e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 129, in _catch_revision_errors
    yield
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 192, in get_revisions
    return self.revision_map.get_revisions(id_)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 359, in _revision_for_ident
    resolved_id)
alembic.script.revision.ResolutionError: No such revision or branch 'bea6982d2a4e'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 49, in <module>
    manager.run()
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/flask_migrate/__init__.py", line 173, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/runtime/migration.py", line 303, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/command.py", line 97, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/autogenerate/api.py", line 369, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/autogenerate/api.py", line 379, in _run_environment
    if set(self.script_directory.get_revisions(rev)) != \
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 192, in get_revisions
    return self.revision_map.get_revisions(id_)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 160, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 121, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/util/compat.py", line 114, in reraise
    raise value.with_traceback(tb)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 129, in _catch_revision_errors
    yield
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/base.py", line 192, in get_revisions
    return self.revision_map.get_revisions(id_)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 299, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/home/raniere/anaconda3/envs/prerit/lib/python3.5/site-packages/alembic/script/revision.py", line 359, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by 'bea6982d2a4e'
```

**Comment by prerit2010** [comment]
@rgaiacs  You already had a db named `result_aggregation.db` in your home directory. 

`python manage.py db migrate` command creates a database if it's not already there and then updates the schema in migrations. But as it found a db present, it did not find the alembic revisions of db in its migrations. So to start fresh, db needs to be deleted as well.

**Comment by ansiqu** [comment]
thanks to @prerit2010 , I solve the issue

**Comment by HiIcy** [comment]
thanks to @prerit2010 ,I have solved the issue yet
